### ISSUE TITLE
CDN Links

### ISSUE THREAD

**Issue by lesichkovm** [antoniandre/wave-ui#101]
Can we have CDN links to install directly for the ones who do not want to deal with NPM?

**Comment by antoniandre** [comment]
Hi @lesichkovm,
Wave UI is already on Unpkg and jsdelivr:
https://unpkg.com/wave-ui
https://unpkg.com/wave-ui@legacy
https://www.jsdelivr.com/package/npm/wave-ui

but I will add it to the documentation to be more explicit though.

**Comment by antoniandre** [comment]
By the way you can look at the implementation of the Codepen demo given for your Vue version in this section:
https://antoniandre.github.io/wave-ui/getting-started#2-import-in-your-project

**Comment by lesichkovm** [comment]
@antoniandre its great these links exist. Can you add these to the installation documentation, so that nobody has to look for them, thanks

**Comment by antoniandre** [comment]
This is now in the documentation.
https://antoniandre.github.io/wave-ui/getting-started#using-a-cdn
