### ISSUE TITLE
Add Feature Scrolling Tabs

### ISSUE THREAD

**Issue by hrydi** [antoniandre/wave-ui#11]
Hellooo,

Thank you for the great UI Framework, i wanna ask something about dynamic tabs.
Can you add scrolling on that, i just try adding a lot of tabs in your demo page and the rest of other tabs doesn't show up.

terima kasih,

**Comment by antoniandre** [comment]
Hi @hrydi, thanks for the feedback.
Your request makes sense. I have added a scrollbar when needed in version 1.13.3 and 2.7.0.

Hope it helps!
Please reopen if not solved.
