### ISSUE TITLE
body.overflow-x: hidden causing extra scrollbar

### ISSUE THREAD

**Issue by res63661** [antoniandre/wave-ui#112]
How to override body{ overflow-x: hidden} ?
This is showing up in my nuxt3 css after adding wave-ui.  I tracked it back to wave-ui.css.  I tried several fixes including what's mentioned in the docs to no avail

**Comment by antoniandre** [comment]
Hi @res63661 sorry I missed your question.
overriding it with `body {overflow-x: auto;}` or `body {overflow-x: initial;}` will do. 
But I am in doubts that this is causing the scrollbar, it should rather be the opposite as overflow-x: hidden suggests. :p
If you want to share a reproduction link, I'll have a look.
Cheers.
