### ISSUE TITLE
Translate pug exemple in HTML

### ISSUE THREAD

**Issue by sMesle** [antoniandre/wave-ui#12]
Hello!

Thanks for sharing this awesome library.

I would like to contribute to the documentation regarding the translation exemple from pug to HTML.

As many people don't already use pug, making this translation will be easier for people using HTML

**Comment by antoniandre** [comment]
Hi @sMesle,

Thanks for your feedback and your help!

As you can guess, building this library and documentation takes time and I haven't found the time yet to convert all the examples.
You are very welcome to contribute in doing so! 🙏 

Just to make sure you know how to start, I'll give you a simple example from `src/documentation/views/ui-components/breadcrumbs/examples.vue`

**Original**

```pug
  example
    w-breadcrumbs(:items="items")
    template(#pug).
      w-breadcrumbs(:items="items")
    template(#js).
      data: () => ({
        items: [
          { label: 'Sitemap', route: '/sitemap' },
          { label: 'Home', route: '/' },
          { label: 'Current page', route: '/w-breadcrumbs' }
        ]
      })
```

**Should become** (only changing in `#html`):

```pug
  example
    w-breadcrumbs(:items="items")
    template(#html).
      &lt;w-breadcrumbs :items="items"&gt;&lt;/w-breadcrumbs&gt;
    template(#js).
      data: () => ({
        items: [
          { label: 'Sitemap', route: '/sitemap' },
          { label: 'Home', route: '/' },
          { label: 'Current page', route: '/w-breadcrumbs' }
        ]
      })
```

In some cases the demo example is slightly different than the one used to build the result in the documentation, please stick to what you see in the example > `template(#pug)`! (it has to export and run correctly in Codepen)

If you have any question, you can ask me here or via email (my email is in the package.json file).

Thank you for your help! 😃
