### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by asb-72** [antoniandre/wave-ui#13]
Hi.

Do you have any plans to realize tables component?

**Comment by antoniandre** [comment]
Hi @asb-72,
Thanks for your interest, yes I will start this component soon!

**Comment by antoniandre** [comment]
Hi @asb-72, I've started the table component. 
For now it has the basic functionality, but just letting you know, it may be enough for you already.

https://antoniandre.github.io/wave-ui/w-table

**Comment by mpricu** [comment]
The table component looks nice. It will be rewritten in HTML?

**Comment by antoniandre** [comment]
Hi @mpricu,
All the components are usable in full HTML for the end user (the developer).
Internally though, this is coded with Pug, but then gets processed before bundling to a public library.
So there is no difference for you!

**Comment by mpricu** [comment]
Hi @antoniandre,

For example this is not working:
`<w-table :items="table.items" :headers="table.headers"> </w-table>`
`<script>
export default {
  setup() {
    const table = {
      headers: [
        { label: "ID", key: "id" },
        { label: "First name", key: "firstName" },
        { label: "Last name", key: "lastName" },
      ],
      items: [
        { id: "1", firstName: "Floretta", lastName: "Sampson" },
        { id: "2", firstName: "Nellie", lastName: "Lynn" },
        { id: "3", firstName: "Rory", lastName: "Bristol" },
        { id: "4", firstName: "Daley", lastName: "Elliott" },
        { id: "5", firstName: "Virgil", lastName: "Carman" },
      ],
    };
    return {
      table,
    };
  },
};
</script>`

**Comment by antoniandre** [comment]
If you are using Vue 3, the `w-table` was not pushed on the Vue 3 branch as still in progress.
I just did a release to include it in version 2.9.0

Here is a Vue 3 demo: https://codepen.io/antoniandre/pen/qBapoOG

**Comment by mpricu** [comment]
Hi @antoniandre,
The w-table is working now but there is a problem: the headers are not aligned with the rows.
Try my github repository, the About tab:
https://github.com/mpricu/wave3demo
I am always using Vue 3. 
There are other components beside w-table which are not yet implemented for Vue 3?
Thank you for your help.

**Comment by antoniandre** [comment]
@mpricu, I looked at your repo, the w-table headers have a css rule to be aligned on the left by default because naturally they would be centered. this is not the case of all the `td` so they dont have useless style on it.
In your page, the content is centered which centers the cells, if you want to align left you need add it in your CSS.
(The choice of not implementing too much CSS is detailed on this page https://antoniandre.github.io/wave-ui/why-wave-ui)

w-table is the only component still marked as `in progress` at the moment, everything is already in the wave-ui@next release!

**Comment by mpricu** [comment]
Yes, 
The content is centered by default since the Vue project is created that way.
I understand your w-table headers have a css rule to be aligned on the left by default.
So how can I center the w-table headers?
Thank you for your help.

**Comment by antoniandre** [comment]
You can just do this:

css

```css
.w-table th {text-align: center}
```

**Comment by mpricu** [comment]
I tried only ".w-table {text-align: center}" and was not working....but with 'th' is working...
Thank you for your help.

**Comment by antoniandre** [comment]
The `w-table` component is now quite stable and functional.
I am closing this issue now, and will continue to improve the component!
