### ISSUE TITLE
W-select issues

### ISSUE THREAD

**Issue by R0N1n-dev** [antoniandre/wave-ui#133]
Been trying to implement a select but having numerous issues and then docs are actually kind of missing on the specifics.
I get errors. Think it as to do with model-value but do not even understand that part of the docs properly.
The javascript examples(as few as they are) dont show the template usage.
![Screenshot from 2023-11-28 13-04-00](https://github.com/antoniandre/wave-ui/assets/83344872/ba2aa0e0-7348-43fa-b2ff-5ba666bb9bd7)
![Screenshot from 2023-11-28 13-03-53](https://github.com/antoniandre/wave-ui/assets/83344872/b1e76ffa-898a-4d28-a348-361a207f0c2e)
![Screenshot from 2023-11-28 13-03-41](https://github.com/antoniandre/wave-ui/assets/83344872/b8a7c7c7-2e38-43fe-807a-181e7d6fe587)
 
Don't know what to do. Some clarification on how to set them up would be appreciated

**Comment by antoniandre** [comment]
Hi @R0N1n-dev,
I've created a Stackblitz for ya here: https://stackblitz.com/edit/waveui-3-wpxs6i?file=src%2FApp.vue where you can see a working w-select with Vue 3 and composition API.
If this doesn't help you, please fork and update the above reproduction link and let me know.

In the future, please share your full code in a reproduction link. That will help me help you faster. ;)

**Comment by R0N1n-dev** [comment]
https://stackblitz.com/github/R0N1n-dev/nuxt-issues for repro. 
Still have issue with my array. Urs works. Mine does not. No idea why
It gives following error 
![Screenshot from 2023-12-13 12-16-46](https://github.com/antoniandre/wave-ui/assets/83344872/e0c40479-0721-4adf-8ea4-c3dea4772330)

**Comment by R0N1n-dev** [comment]
BTW it also gives the same error on attempting to use w-icon component always.

**Comment by R0N1n-dev** [comment]
Wave 3 docs really removed alot of js stuff. mostly see pug templates. This is just weird and dont see the reason for it..
