### ISSUE TITLE
Pagination for w-table should collapse or hide when there are many pages

### ISSUE THREAD

**Issue by Fleximex** [antoniandre/wave-ui#136]
When there are many pages in a w-table the pagination buttons are all visible.
![Screenshot 2024-01-04 at 16 03 36](https://github.com/antoniandre/wave-ui/assets/9057329/1ce328e0-769c-44d2-8c1a-38cb88134cc8)
The default behavior for pagination is for pages that are distant from the current page to hide into a ... button.
![Screenshot 2024-01-04 at 16 06 16](https://github.com/antoniandre/wave-ui/assets/9057329/35367656-6d5d-4778-944a-96f6b481e9ec)
Or for example to not show up:
![Screenshot 2024-01-04 at 16 09 56](https://github.com/antoniandre/wave-ui/assets/9057329/eccfa6fe-a058-48c4-8d2f-c810f726c4f2)

Could any of these be implemented to prevent the cluttered UI like in the first image?

**Comment by antoniandre** [comment]
Hi @Fleximex,
The pagination was indeed in progress.
I took the opportunity to finish/improve what needed to be and have accomplished a similar layout and feature, now released in version 3.9.2.
Please check the pagination documentation for details: https://antoniandre.github.io/wave-ui/w-table#pagination.
I hope it solves the issue, if not please reopen :)

**Comment by Fleximex** [comment]
The behaviour is still unclear. When does it trigger?

For me, it only works when settings the total and only when the total is more than the actual data I have (of course resulting in empty pages). It doesn't make sense.
