### ISSUE TITLE
Pagination Slot for w-table

### ISSUE THREAD

**Issue by Fleximex** [antoniandre/wave-ui#137]
I would be nice to be able to edit the pagination UI of a w-table by providing a custom template.
For example `<template #pagination=`

Similar to how it is now implemented for Footers, Headers, Row Cells, etc.

**Comment by antoniandre** [comment]
Hi @Fleximex,
The pagination slot was actually already existing but the documentation was missing.
I took the opportunity to review all the pagination and finish/improve what needed to be, now released in version 3.9.2.
Please check the pagination documentation for details: https://antoniandre.github.io/wave-ui/w-table#pagination, as well as the new example about the custom pagination.

**Comment by antoniandre** [comment]
I hope it solves the issue, if not please reopen :)
