### ISSUE TITLE
[w-select] Enabling text input

### ISSUE THREAD

**Issue by alessandrodipierro** [antoniandre/wave-ui#139]
Similarly to the new w-autocomplete component, it would be very useful to be able to start writing the text of the option to select to filter the drop-down list or alternatively it would be useful if w-autocomplete had the same styles as all the rest of the form components

**Comment by antoniandre** [comment]
Hi @alessandrodipierro this is now possible to lookup a **w-select** list item and preselect it (gains focus) by typing its first characters (case insensitive).
Released in version 3.10.0

Hope it helps!
