### ISSUE TITLE
w-notification does not hide on timeout if initially shown

### ISSUE THREAD

**Issue by mpricu** [antoniandre/wave-ui#15]
The notification will be rewritten in HTML?
Thank you.

**Comment by antoniandre** [comment]
Hi @mpricu,
All the components are usable in full HTML for the end user (the developer).
Internally though, this is coded with Pug, but then gets processed before bundling to a public library.
So there is no difference for you!

In the documentation the examples source code are currently in Pug, so they will be translated to HTML for a larger public. This does not change anything to the fact that you can fully use it in plain HTML. :)

Let me know if you have other questions!

**Comment by mpricu** [comment]
Hi @antoniandre,
My problem is I cannot customize the notification in plain HTML ( for example timeout, background color etc).
This template in HTML is not working for me:
<template>
  <w-notification
    timeout="1500"
    bg-color="green"
    plain
    round
    shadow
    bottom
    right
  >
    {{ message }}
  </w-notification>
</template>

Thank you for your help.

**Comment by antoniandre** [comment]
Hi @mpricu, 
I think you are using Vue 3, let me know otherwise.
This is an example of how to use a `w-notification` on Vue 3: https://codepen.io/antoniandre/pen/RwaXMLd?editors=1010
You can click on the star rating to see the notification in action.

Hope it helps.

**Comment by mpricu** [comment]
Hi @antoniandre,
The notification still not taking any parameters, with (:timeout ="1000") or without v-bind (timeout ="1000").
I have a github repository and you can see with your eyes:
https://github.com/mpricu/wave3demo
I am always using Vue 3.
Thank you for your help.

**Comment by antoniandre** [comment]
@mpricu, after checking your example, I can see this is a bug. In this case the timeout is not applied when the notification is initially shown. 
I'll release a patch soon, thanks for reporting!

**Comment by antoniandre** [comment]
Should be fixed now in version 2.9.1

**Comment by mpricu** [comment]
Yes,
The timeout is working now, but I could not make bg-color to work.
Can you show me how to change the bg-color in my project?
Thank you for your help.

**Comment by antoniandre** [comment]
I've added this option in 2.9.2, there was a default white background if not using an alert type.
Let me know if you have other questions.

**Comment by mpricu** [comment]
I tried to customize bg-color and color properties with version 2.9.2 and it is working.
I have a design question: why I should use v-bind shorthand (":bg-color") for w-notification and not for the w-button ("bg-color") ?
Should not be consistent ?

**Comment by antoniandre** [comment]
You can use use `v-bind` or `:` for variables in Vue or just `bg-color` without binding if it does not need to be interpreted. This is your call.

This would work:

```vue
    <w-notification v-model="showThankYou" bg-color="green">
      Thank you!
    </w-notification>
```

**Comment by mpricu** [comment]
Yes, you are right. I was confused by the bug.
Thank you for your work.
