### ISSUE TITLE
w-confirm not work on version wave-ui 3.13.4

### ISSUE THREAD

**Issue by ismailaya** [antoniandre/wave-ui#156]
I have created project before with wave-ui and w-confirm work file. After upgrading to wave-ui 3.13.4 ,I detect that all section I use  w-confirm component not work at all.
What the problem?
is there any break changes?

**Comment by antoniandre** [comment]
Hi @ismailaya,
Thanks for reporting.
I indeed fixed a regression with the w-confirm not opening the menu, but I'm not sure that's the issue you're talking about.
In the last few versions of Wave UI, I upgraded the Vue dev dependency which leaded to the needed development of the versions 3.13.x to remove some new Vue warnings.
If after upgrading to Wave UI 3.13.5 you are still facing an issue, it could be that you need to update your Vue.
If the issue persists, please share a reproduction example. You can branch off of a working Codepen example if needed: https://antoniandre.github.io/wave-ui/w-confirm#basic

Cheers!

**Comment by ismailaya** [comment]
Now working fine, thanks

**Comment by ismailaya** [comment]
Thank you brother, now it work fine
