### ISSUE TITLE
Support for tree shaking ?

### ISSUE THREAD

**Issue by soulsam480** [antoniandre/wave-ui#19]
Hii @antoniandre amazing library. Will be much better if it supports tree shaking. Any plan to add the same ?

**Comment by antoniandre** [comment]
Hi @soulsam480, thanks for your feedback. 
Yes indeed it's in the plans, I'll start this soon.
Please let me know what you're using Wave UI with: like Vue 2, Vue 3, Nuxt.

**Comment by soulsam480** [comment]
I'm using Wave UI with Vue 3

**Comment by antoniandre** [comment]
Hi @soulsam480,

The _à la carte_ feature is now live and allows tree-shaking for both Vue 2 and Vue 3!
https://antoniandre.github.io/wave-ui/getting-started#a-la-carte

Hope it helps!

Please reopen if not solved. :)
