### ISSUE TITLE
w-dialog width does not accept strings

### ISSUE THREAD

**Issue by nickmcm92** [antoniandre/wave-ui#22]
The [documentation ](https://antoniandre.github.io/wave-ui/w-dialog#width) states that width
> Accepts a string made of a value and a unit (e.g. `2.5em`) or a number (e.g. `45`) that will be a pixel value.

However, using a string produces the warning 
```
Invalid prop: type check failed for prop "width". Expected Number with value NaN, got String with value "2.5em". 
```

I have tested using both Vue 2 & Vue 3, using Wave UI version 1.20.3

A demo of this can be found at [this codepen](https://codepen.io/nickmcm92/pen/abBZjZp?editors=0001)

**Comment by antoniandre** [comment]
Hi @nickmcm92,
Thank you for reporting and for taking the time to do a perfect bug report with information and repro! 👍 
This is now fixed in version 1.20.5 for Vue 2, and version 2.12.0 for Vue 3.
Let me know if it helped, please reopen otehrwise! :)
