### ISSUE TITLE
Vue 3 Customisation via SCSS

### ISSUE THREAD

**Issue by BrianBut** [antoniandre/wave-ui#23]
Following your instructions for customisation I immediately ran into this error! HELP! 
It does not help that the cited webpack site is currently unreadable.

 ERROR  Failed to compile with 1 error                                                                                               06:22:14
 error  in ./node_modules/wave-ui/src/wave-ui/index.js

Module parse failed: Unexpected token (14:18)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| export default class WaveUI {
>   static instance = null
|   static registered = false
| 

 @ ./src/main.js 8:0-41 14:4-10
 @ multi (webpack)-dev-server/client?http://192.168.1.80:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by antoniandre** [comment]
Hi @BrianBut,
The error you are facing comes from not transpiling the JavaScript, and this syntax is new Javascript features.

You may have missed a part in the documentation: https://antoniandre.github.io/wave-ui/customization
I also added some more information in this documentation page to make it clearer. 

Make sure to install the dev dependencies as explained, with sass-loader@10 not 11.
Hope it helps.

**Comment by antoniandre** [comment]
Closing the issue now. Please reopen if not solved.
