### ISSUE TITLE
WCAG/Section 501 support

### ISSUE THREAD

**Issue by userquin** [antoniandre/wave-ui#25]
Is there any plan to implement WCAG/Section 501 (accesibility)?

For example, when focusing `w-select`, it MUST respnd to arrow up/down keys...

**Comment by antoniandre** [comment]
Hi @userquin, the accessibility work is done everywhere, I may have missed some aspects though.
The keyboard arrows is already implemented when the select is open (and to open close), but not the arrows navigation while it's closed. I will definitely add this soon. :)

Let me know if you notice anything else.

**Comment by userquin** [comment]
Focus it with keyborad, not with the mouse (the popup must not be shown): a native select, when focused, using arrow up and arrow down, just select next/previous option, while `ws-select` do not.

**Comment by userquin** [comment]
and sorry, I do not read complety your comment...

**Comment by antoniandre** [comment]
Hi @userquin, 
From version 1.21.0, it is now possible to select an item from the w-select list with keyboard up and down arrows while the list is closed but on focus.
Hope it helps!

Closing the issue now, please reopen if not solved.

**Comment by userquin** [comment]
@antoniandre 

It is solved, but remove rewind, that is, when reach first/last entry, stop selecting last/first respectivelly.

How can I reopen it?
