### ISSUE TITLE
Accordion changes the page position

### ISSUE THREAD

**Issue by bbugh** [antoniandre/wave-ui#3]
Hi 👋. I was looking around for different component libraries for Vue and saw this one. I noticed that expanding/ accordion sections on the front page changes the page scroll position, at least on Chrome: 

https://antoniandre.github.io/wave-ui/

Seems like a bug!

**Comment by antoniandre** [comment]
Hi @bbugh,

Thanks for reporting. This is a natural browser behavior, happening with the `expand-single` option only.
I have released a patch though to prevent this undesirable scroll: **1.12.1**.

> https://antoniandre.github.io/wave-ui/release-notes

You can retry on the home page, should be fine now. ;)

Hope it helps.

**Comment by antoniandre** [comment]
Closing the issue now that it's patched. Please reopen if not solved.
