### ISSUE TITLE
Allow sticky columns in w-table

### ISSUE THREAD

**Issue by paulsimongb** [antoniandre/wave-ui#36]
Hi 

This is not really an issue, more of a comment / feature request.

I know that the Table is still under development, but as bare minimum for us, it would need to have a facility to fix the left most n columns as we are looking for a table to display results of multi-dimensional data, where the number of columns that need to be fixed will vary depending on how many dimensions are nested in the column area and how many attributes each of those dimensions has. Similarly the number of columns with figures will also vary depending on the query. At present we are using DexExtreme's DataTable which seems to give us most of what we want, although it is quite a large download.

There are a lot of tables that cater for the standard product list and I think your table will that

**Comment by antoniandre** [comment]
Thanks for your suggestion @paulsimongb!
I will think about it and its feasibility in a lightweight way and will let you know.

**Comment by antoniandre** [comment]
Also if you can provide an example or screenshot of what you have in mind that will help making sure I understand the same!

**Comment by paulsimongb** [comment]
Hi Antoni

This essentially the same thing as the FreezePanes facility in Excel 

This is a screen shot of a tool I work with

![image](https://user-images.githubusercontent.com/26175830/110853891-1304ce80-82ac-11eb-99c2-fec8e3793d19.png)

What I am looking for  is the ability to mark the left most columns as fixed, which then means when scrolling horizontally the fixed columns stay visible and the other columns scroll away behind them.

**Comment by antoniandre** [comment]
Hi @paulsimongb, sorry for late reply.
This feature is now available in the version 2.41.0

https://antoniandre.github.io/wave-ui/w-table#sticky-columns

Please reopen if not solved :)
