### ISSUE TITLE
Ability to mark entire form as read-only or disabled

### ISSUE THREAD

**Issue by djmattyg007** [antoniandre/wave-ui#38]
It would be nice if we could set a "read-only" prop on a `w-form` element and have it automatically make all wave-ui form elements inside of it read-only, rather than having to manually set it for each element individually. The same applies to "disabled".

**Comment by djmattyg007** [comment]
As per #40, I’m using Vue 3.

**Comment by antoniandre** [comment]
Hi @djmattyg007,

This is now an option in version 1.26.0 (Vue 2) and 2.15.0 (Vue 3) 
You can refer to this example: https://antoniandre.github.io/wave-ui/w-form#disabled-and-readonly-form

Hope it helps, please reopen if not solved!
