### ISSUE TITLE
Display notifications with this.$waveui.notify()

### ISSUE THREAD

**Issue by djmattyg007** [antoniandre/wave-ui#39]
Instead of having to create `w-notification` elements in potentially deeply nested components and worry about having them overlap with other notifications and so on, it would be nice if notifications could be triggered from anywhere with a function call, and have them centrally managed.

Ideally, notifications would also never overlap. If a notification was triggered while another one was still visible, they should be automatically arranged such that they are both always visible.

**Comment by djmattyg007** [comment]
As per #40, I’m using Vue 3.

**Comment by antoniandre** [comment]
Also related to #14, now considering this feature request.

**Comment by antoniandre** [comment]
Hi @djmattyg007, @mikeerickson, @Epithumia, @HenryLin0914.
This is now possible in Wave UI 1.35.0 and 2.21.0.

Check the documentation at https://antoniandre.github.io/wave-ui/w-notification!

Thanks for suggesting this feature, and please reopen if you see any issue. :)

**Comment by turbobuilt** [comment]
HI @antoniandre we still need a pretty confirm/prompt dialog box.  I have hacked one using w-dialog, and I had to create a new instance of WaveUI every time to make it work right.  It would be nice if there was a simple w-dialog prebuild with a confirm capability.
