### ISSUE TITLE
Sass, not SASS

### ISSUE THREAD

**Issue by TheJaredWilcurt** [antoniandre/wave-ui#4]
The proper orthography is `Sass`, it is never put in all caps, whether referring to the language, the syntax, or the file extension (`.sass`).

**Comment by antoniandre** [comment]
Yeah right, thanks for correcting!
That's funny because SCSS gets an all caps and Sass doesn't, yet they are both acronyms.
I've updated the documentation, now using `Sass`.

**Comment by TheJaredWilcurt** [comment]
I think the history of it is "Sass" the language was created, and only had one syntax. They later did a Backronym of it to mean "Syntactically Awesome Style Sheets". And eventually created the second syntax to make it easier for people to transition. Because they wanted to enforce the syntax at a file level, and were already using `.sass`, they adopted `.scss` and just called it "Sassy CSS". but I don't think it was ever a conscious decision to make the `.sass` files be called "Sass" syntax, which is why they still refer to it at "indented syntax", to avoid confusion. but it's still kinda confusing.
