### ISSUE TITLE
Form is validated after submit event is fired

### ISSUE THREAD

**Issue by djmattyg007** [antoniandre/wave-ui#40]
I'm pretty sure lines 148 and 149 should be swapped:

https://github.com/antoniandre/wave-ui/blob/ee9aa1f3e5cd9bbe86583f5fd07c04801e486a75/src/wave-ui/components/w-form.vue#L149

**Comment by antoniandre** [comment]
Looks like a solid track @djmattyg007! 
Thanks for your feedback, I'll have a closer look soon.

But if you need to trigger some actions when the form is submitted, you should use @validate or @success or @error on the form tag.  These events are callback from Wave UI after validating.

Here: https://antoniandre.github.io/wave-ui/w-form#on-validate-on-success-and-on-error-events

**Comment by djmattyg007** [comment]
I probably should have provided some more context in my original issue sorry. Here's the set of steps I was following:

1. Create a `w-form` with the prop `no-keyup-validation` set, and the `v-model` value set to `null` (the default).
2. Make sure the form data for all form elements is actually already valid, so the form should validate successfully without the user doing anything. This is common for an "edit" form.
3. Click a `w-button` with `type="submit"` to submit the form.
4. Submit observer is called. The form's `v-model` value is still `null`, which means it isn't `true`. Submit observer rejects the submission attempt because the form isn't considered valid.
5. Form is validated, and validates successfully.
6. User clicks submit button again without changing anything, and it succeeds.

So this is solely about ensuring validation and submission happen in the correct order.

**Comment by antoniandre** [comment]
Absolutely right. Thanks for reporting and pointing in the right direction!
Now fixed in version 1.25.1 (if you use Vue 3 please mention in the issues you create!)

Please reopen if you still see an issue!

**Comment by djmattyg007** [comment]
Probably worth mentioning that I do use Vue 3 exclusively at the moment :) Thank you for this software by the way!

**Comment by antoniandre** [comment]
Cool, so I released 2.14.1 for this change!
Thanks for the feedback!
