### ISSUE TITLE
datapicker

### ISSUE THREAD

**Issue by zfranco55** [antoniandre/wave-ui#42]
is it possible to use only datapickers, instead of the calendar?

**Comment by antoniandre** [comment]
Hi @zfranco55,
Are you talking about date picker, but not using vue-cal external calendar?
If so, you can check the w-input field that accepts the default "date" type: https://antoniandre.github.io/wave-ui/w-input#types.
Let me know if that's not what you're looking for.

**Comment by zfranco55** [comment]
I'm sorry for not reading the whole paragraph on text input. I assumed, as
with other libraries that it was a separate component.
I would also ask you if in the table you can make an example of a global
filter (in all fields / columns) a variable like SQL query "% like%"

Il giorno gio 11 mar 2021 alle ore 15:10 Antoni ***@***.***>
ha scritto:

**Comment by antoniandre** [comment]
Hi @zfranco55, no problem for the input.
Regarding the `w-table` global filter, I've added this example in the documentation :)
https://antoniandre.github.io/wave-ui/w-table#global-filter

Hope it helps!

**Comment by zfranco55** [comment]
is what I was looking for.
Thank you very much, also for the speed with which you answered me.

Il giorno gio 11 mar 2021 alle ore 23:46 Antoni ***@***.***>
ha scritto:
