### ISSUE TITLE
Table multi-select

### ISSUE THREAD

**Issue by djmattyg007** [antoniandre/wave-ui#45]
It would be nice if there was an ability to select multiple entries in a table at the same time. This is often useful for powering batch operations.

**Comment by antoniandre** [comment]
Definitely. I had that in mind too.

**Comment by antoniandre** [comment]
Hi @djmattyg007,

This is now possible in version 1.27.0 (Vue 2) and 2.16.0 (Vue 3).
You can refer to this example: https://antoniandre.github.io/wave-ui/w-table#rows-selection

Hope it helps, please reopen if not solved!
