### ISSUE TITLE
Ability to reset selected rows

### ISSUE THREAD

**Issue by djmattyg007** [antoniandre/wave-ui#48]
Selected rows stay selected even after the contents of the table have been updated. It would be nice to be able to reset the selection when the list of items changes.

I'm using Vue 3.

**Comment by antoniandre** [comment]
Hi @djmattyg007,

In the new version 2.17.0, you can easily reset them now via the `v-model:selected-rows` array.
https://antoniandre.github.io/wave-ui/w-table#updating-the-selected-rows-programmatically

Hope it helps, please reopen if not solved. :)
