### ISSUE TITLE
w-table: ability to select a row programmatically

### ISSUE THREAD

**Issue by lecneri** [antoniandre/wave-ui#50]
How to select a table's row with js?
I've tried to set selected rows property but didn't work

**Comment by antoniandre** [comment]
Sorry I can't help you with so little information.
Please share your code, if you rare using Vue 2 or 3, and if you are talking about the w-table component that should also be in the question! Thanks :)

**Comment by antoniandre** [comment]
Hi @lecneri, I understand your request. At the moment this is not possible as still in progress, but I'll add that soon! :)
Will let you know.

**Comment by antoniandre** [comment]
Hi @lecneri,

This is now possible in version 1.31.0 (Vue 2) and 2.17.0 (Vue 3).
https://antoniandre.github.io/wave-ui/w-table#updating-the-selected-rows-programmatically

Hope it helps!
Please reopen if not solved :)

**Comment by lecneri** [comment]
@antoniandre thank you! I'll try it out!
