### ISSUE TITLE
Global alert, confirm, prompt dialogs (mixins)

### ISSUE THREAD

**Issue by mikeerickson** [antoniandre/wave-ui#51]
I am curious if global methods exist (mixin) to display these various dialogs, something like

```js
this.$alert('hello world');
this.$confirm('hello world',{okButton: 'Yup', cancelButton: 'Nope'});
this.$prompt('What is your name?',{default: 'Mike'});
```

**Comment by antoniandre** [comment]
Hi @mikeerickson thanks for your interest.
At the moment it does not exist. but since you are not the first one who asks, I'm considering to add something to help.

Please add a voice in #39 and follow the thread there. :)
