### ISSUE TITLE
Async form validation

### ISSUE THREAD

**Issue by nmauersberg** [antoniandre/wave-ui#55]
Hey there!
I am struggeling to implement an async validation method. Any idea how I would do that? :)

```js
...
validators: {
  checkUsername: (value) => this.asyncMethodToCheckUsername(value) || 'Username already taken!'
}
...
```

The method returns `undefined` when called as validator, but `true` or `false` when called from somewhere else.

When using the validator as an async function like this, result.data contains `true` or `false`, but no errors are triggered.

```js
...
validators: {
  checkUsername: async (value) => {
      const result = await this.$store.dispatch('auth/checkUsername', value);
      return result.data || 'Username already taken!';
    },
}
...
```
Any hint would be much appreciated!

It's fun to work with your Library by the way!

**Comment by antoniandre** [comment]
Hi @nmauersberg,

Thanks for your feedback and support! 😃 
This is a good question and use-case! It's actually not possible as is.
But I'm working on it to support `async` functions, will let you know when done!

**Comment by nmauersberg** [comment]
Awesome! Thank you :)
Have a great weekend!

**Comment by antoniandre** [comment]
Hi @nmauersberg,

This is now possible in version 1.32.0. (if you're using Vue 3, I'll release it over the weekend)
https://antoniandre.github.io/wave-ui/w-form#asynchronous-validations

Just FYI, I will soon work on adding the ability to display validation messages that are not errors, and adding a loading option on the input field (while waiting for a server response).

Hope it helps, let me know if you still can't make it work!

**Comment by nmauersberg** [comment]
Thank you very much! <3
Works like a charm!

**Comment by nmauersberg** [comment]
Hi @antoniandre :)

I have a small issue with the new version. Somehow my form does not send any data anymore, triggered by `@success`. When I downgrade, it works again. Even without async validation. Is this a bug?

Here is my vue component: https://gist.github.com/nmauersberg/d0bbf03a53ca9c420b9331eca4393a59#file-login-vue

When I implement your demo code, i get the following error:
`The form has [object Promise]0 errors.`

Cheers!

**Comment by antoniandre** [comment]
Hi @nmauersberg, thanks for reporting the issue!
Taking a closer look at it, it's actually way more complex than just adding async/await everywhere. :/ 
I could fix the problem you are now seeing, and also keeping the async validators, but introducing async functions slows down the validations to the next tick (like a setTimeout of 0 per say), which creates a delay while typing in a field and quickly toggles the validation messages up and down (like it's vibrating while you type in). Can't release it this way!

So I have to revert for now, I can't leave the form validation broken. But I'll keep working on a solution and will keep you posted.

Cheers.

**Comment by nmauersberg** [comment]
Okay, cool! Thanks for looking into it and for the explaination. Take your time! :)
Have a great weekend.

**Comment by antoniandre** [comment]
@nmauersberg,

I've released a patch where everything should be working. I've checked all the examples.
let me know if there's anything else!

**Comment by nmauersberg** [comment]
Wow, cool! It works really well now. I went through your commit and the solution is really elegant. :)

Thank you! <3

**Comment by antoniandre** [comment]
That's awesome! 😎 
I'm closing the issue then, don't hesitate to reopen if you notice anything wrong.

btw, I've also added the `loading` option on a `w-input`, same documentation link: https://antoniandre.github.io/wave-ui/w-form#advanced-validation

Cheers!
