### ISSUE TITLE
The `label-on-left` property of `w-switch` makes it look like always off

### ISSUE THREAD

**Issue by GuDzpoz** [antoniandre/wave-ui#59]
This is a functioning example of `w-switch` without `label-on-left`:
![wave-ui-1](https://user-images.githubusercontent.com/14026120/122776895-0a546900-d29b-11eb-9122-26472c120d42.gif)
But with `label-on-left`, its behavior is really curious: (the v-model value is changing but just cannot be tell from the look)
![wave-ui-2](https://user-images.githubusercontent.com/14026120/122776901-0c1e2c80-d29b-11eb-82b4-da4002e0b3a6.gif)

The browser is `Mozill Firefox 87.0b1 (64-bit)`. And I can reproduce this on `Google Chrome 88.0.4324.182 (Official Build) (64-bit)`.
I am currently using `wave-ui@next` (`wave-ui@2.19.6`) and the examples (see below) in CodePen seems to be using `https://unpkg.com/wave-ui@latest`, that is `wave-ui@1.33.0`.

Anyway, thank you for your hard work on this brilliant project!

### A way to reproduce

Go to [https://antoniandre.github.io/wave-ui/w-switch](https://antoniandre.github.io/wave-ui/w-switch). And from any of the examples, go to a corresponding CodePen editor and make one `w-switch` `label-on-left` with an arbitrary label. And the switch will look like always off.

**Comment by antoniandre** [comment]
Thanks for your feedback and for reporting bug @GuDzpoz!
You're right, and your issue report is very clear & helpful 👍 
I'll fix this soon and will let you know.

**Comment by antoniandre** [comment]
Hi @GuDzpoz, this is now fixed in version 1.34.2!
Please reopen if not solved. :)
