### ISSUE TITLE
Request for a clearer 'Getting Started' for beginners

### ISSUE THREAD

**Issue by BrianBut** [antoniandre/wave-ui#6]
I have failed to install and run a wave-ui project. I need a clear step by step example to get my first wave-ui app running. Perhaps the most mysterious paragraph section 3 of the installation. -- Place a 'w-app at the route of your app' -- in a file named 'App.js'
The structure of the documentation itself has been of little help as it places the <w-app> in /documentation/index.vue. 
Have you any plans for such a 'step by step to your first wave-ui app'?

**Comment by antoniandre** [comment]
Hi @BrianBut,

No problem, I'll write a more detailed install step by step.
Are you trying to add Wave UI in a Vue 2 project or Vue 3?
What is your environment? Vue CLI, Webpack, Vite, Nuxt, etc.

If you are using Vue 3, this is a good example to start with: https://codepen.io/antoniandre/pen/RwaXMLd?editors=1010

**Comment by BrianBut** [comment]
Hi Antoni
Thanks for your prompt response.
I am trying to use 'npx @vue/cli create my-first-wave-ui-app'  with vue 3,.
dependencies": { "core-js": "^3.6.5", "vue": "^3.0.0", "vue-router":
"^4.0.0-0",  "wave-ui": "^2.6.0"}
The codepen pages do not help with my problem of building a running
app as they leave me with the same issue.

**Comment by antoniandre** [comment]
@BrianBut,

Here's a detailed step by step tailored for your environment.
I'll add a little more details in the docs as well.

Starting with a fresh install, select Vue 3.
<img width="488" alt="Screen Shot 2020-11-19 at 10 03 46 pm" src="https://user-images.githubusercontent.com/22971289/99659541-1b46bd00-2ab5-11eb-8b9d-034f0bb56d63.png">

<img width="816" alt="Screen Shot 2020-11-19 at 10 03 57 pm" src="https://user-images.githubusercontent.com/22971289/99659547-1e41ad80-2ab5-11eb-8cb5-15312b23fa47.png">

<img width="508" alt="Screen Shot 2020-11-19 at 10 04 53 pm" src="https://user-images.githubusercontent.com/22971289/99659552-1f72da80-2ab5-11eb-9921-67a611e9c22a.png">

Run the suggested commands...
<img width="708" alt="Screen Shot 2020-11-19 at 10 05 47 pm" src="https://user-images.githubusercontent.com/22971289/99659554-200b7100-2ab5-11eb-8e24-06258f852323.png">

All good, the App is ready and running. Open the project in an editor.
<img width="1502" alt="Screen Shot 2020-11-19 at 10 07 57 pm" src="https://user-images.githubusercontent.com/22971289/99659558-20a40780-2ab5-11eb-88bd-edbd4bee3290.png">

Install wave-ui with `npm i --S wave-ui@next`. (`next` for Vue 3 project)
<img width="887" alt="Screen Shot 2020-11-19 at 10 08 22 pm" src="https://user-images.githubusercontent.com/22971289/99659564-24378e80-2ab5-11eb-9dc4-1ca484385595.png">

<img width="1540" alt="Screen Shot 2020-11-19 at 10 12 55 pm" src="https://user-images.githubusercontent.com/22971289/99659566-24d02500-2ab5-11eb-92c4-5d23e57297cc.png">

Copy the Vue 3 snippet from Wave UI documentation to place in main.js
<img width="614" alt="Screen Shot 2020-11-19 at 10 14 00 pm" src="https://user-images.githubusercontent.com/22971289/99659570-26015200-2ab5-11eb-9f35-032cf03f8a21.png">

Paste it in main.js replacing the content already there. (pay attention to the capital letter in `App.vue` in a new project - I never put uppercase in file names)
<img width="1551" alt="Screen Shot 2020-11-19 at 10 14 10 pm" src="https://user-images.githubusercontent.com/22971289/99659571-2699e880-2ab5-11eb-983e-7a171928b1b2.png">

<img width="1536" alt="Screen Shot 2020-11-19 at 10 14 32 pm" src="https://user-images.githubusercontent.com/22971289/99659573-27327f00-2ab5-11eb-86d5-42ee05805e0f.png">

Now go to the `App.vue` that looks like that...
<img width="1549" alt="Screen Shot 2020-11-19 at 10 14 59 pm" src="https://user-images.githubusercontent.com/22971289/99659577-2863ac00-2ab5-11eb-9238-5d09a227b675.png">

And add a wrapping `<w-app>` tag. Voilà!
<img width="1552" alt="Screen Shot 2020-11-19 at 10 15 12 pm" src="https://user-images.githubusercontent.com/22971289/99659583-2994d900-2ab5-11eb-84c7-9f15c4c955b0.png">

Here is the result in the browser.
<img width="1191" alt="Screen Shot 2020-11-19 at 10 15 41 pm" src="https://user-images.githubusercontent.com/22971289/99659589-2ac60600-2ab5-11eb-9222-59540df6fcb7.png">

**Comment by BrianBut** [comment]
Thanks for that! I now have a working first app!. The crucial line was the import on line 2 of main.js. "import App from './App.vue'" works. "import App from './app'" from the documentation does not.

**Comment by antoniandre** [comment]
I have update the documentation to show the standard `import App from './App.vue'`.

**Comment by BrianBut** [comment]
This is a big improvement. Thank You!. The documentation seems to be
improving daily. Well done. Now its just me being slow to grasp it
all.
Brian
