### ISSUE TITLE
[Feature Request] `keep-alive`-like support for `w-tabs`

### ISSUE THREAD

**Issue by GuDzpoz** [antoniandre/wave-ui#65]
Currently it seems tab contents are getting created each time one switches a tab. (See https://codepen.io/gudzpoz/pen/PojYJMv for an instance: each `w-switch` is a new switch and the `w-accordion` state is not preserved.) When the content is big, re-rendering each time is inefficient and an effect like `keep-alive` or `v-show` might be desirable.

**Comment by antoniandre** [comment]
Hi @GuDzpoz, that makes sense.
Adding this to my todo. :)

**Comment by antoniandre** [comment]
Hi @GuDzpoz, @macjuul,

Thanks for your feature request and clear example on Codepen 👍 
This is now implemented in version 1.40.0 (You can rerun your Codepen).

Hope it helps, please reopen if not solved. :)
