### ISSUE TITLE
wave-ui + Nuxt + Vue 3

### ISSUE THREAD

**Issue by SimonKib** [antoniandre/wave-ui#66]
Hello

You documentation says that Nuxt does not yet support Vue 3 and therefore your documentation is for Vue 2. But since writing that, Nuxt now support Vue 3. Could you update your documentation, to make it easy for for Nuxt + Vue 3 users to implement your impressive framework?

Ref: https://antoniandre.github.io/wave-ui/getting-started#installation-on-nuxt

**Comment by antoniandre** [comment]
Thanks for your feedback @SimonKib, and that's right now we have Nuxt 3 🎉 I need to update the docs and test Wave UI on Nuxt 3.
Have you tested it yet?

I've been very busy lately, but I'll get back to it soon :)

**Comment by DerrikMilligan** [comment]
It does not currently work when following the instructions. You get this error.
![image](https://user-images.githubusercontent.com/37845846/142718281-d033e0bb-2f32-4cc6-b145-cc742c44acac.png)

**Comment by tintin10q** [comment]
Any updates on this?

**Comment by R0N1n-dev** [comment]
I have a repo with Nuxt 3 set up with wave UI.
https://stackblitz.com/R0N1n-dev/
nuxi-wave
But on running the server, it reuns well but for an error about Hydration mismatch as shown in the screenshot below.
And it causes issues with hot-reloading.(have to reload page after saving code sometimes).

![Screenshot from 2023-06-07 10-24-04](https://github.com/antoniandre/wave-ui/assets/83344872/f5506b1c-b517-4ad6-bc86-dbeea3cf1f60)

**Comment by antoniandre** [comment]
Hi @R0N1n-dev, great thanks for the repro - but it doesn't seem to be public, I can't access it.
If you share again, I'll have a look soon.

**Comment by R0N1n-dev** [comment]
https://stackblitz.com/github/R0N1n-dev/nuxi-wave
Sorry forgot the github part
