### ISSUE TITLE
Feature Request: Pop Confirm Component

### ISSUE THREAD

**Issue by BroJenuel** [antoniandre/wave-ui#68]
Having this component is really awesome for confirming something before proceeding.
![image](https://user-images.githubusercontent.com/31676163/136313400-c71a48a8-d676-46c7-9a89-7513b87d3dfb.png)
![image](https://user-images.githubusercontent.com/31676163/136313435-d2fdf626-4a8f-47ee-b5c5-e6a815d0eef0.png)

**Comment by antoniandre** [comment]
Hi @BroJenuel, @macjuul,
This component is now released! 
https://antoniandre.github.io/wave-ui/w-confirm
I might just change a couple of small things while this is still marked as in progress, and I will update the API documentation soon and release for Vue 3.
But the features and examples are there.

Let me know if you have feedback.
Hope it helps. :)

**Comment by BroJenuel** [comment]
Awesome!!! Nise!!
