### ISSUE TITLE
about w-drawer

### ISSUE THREAD

**Issue by HenryLin0914** [antoniandre/wave-ui#7]
Is there an event before closing the drawer?

Can events be used to determine whether to close the drawer ?

thank u !!

this ui is very powerful !!!

**Comment by antoniandre** [comment]
Hi @HenryLin0914,
Thanks for your feedback.

There is a fired `close` event: https://antoniandre.github.io/wave-ui/w-drawer#close.
Also you can dictate the open or close state of the drawer via the `v-model` that's the simplest and recommended way.

But what are you exactly looking for? I can better help if you tell me what you are trying to do. :)

**Comment by HenryLin0914** [comment]
@antoniandre Thanks for your reply.
But we actually want a trigger to control drawer close or not in the close event.
Like event with params, or retrun false could cancel the close function.

Any recommendation will be grateful.
Have a nice day. :)

**Comment by antoniandre** [comment]
@HenryLin0914, 
If I understand well, your condition to cancel the drawer closing should be in the `:persistent` attribute.
https://antoniandre.github.io/wave-ui/w-drawer#persistent-drawers

With `persistent` set to true, the user outside clicks will not close the drawer.
Ex:

```html 
<w-drawer :persistent="shouldStayOpen">
```

```js
// In methods or computed.
shouldStayOpen () {
    return false // Or true on the condition you want.
}
```

If you have added external buttons to toggle the drawer you can also apply the same `shouldStayOpen` condition to dismiss the user click when you want.

If it is not what you are looking for, please be clearer in the explanation!

**Comment by antoniandre** [comment]
Closing the issue due to inactivity.
Please reopen if not solved.

**Comment by HenryLin0914** [comment]
Hi antoniandre !

we can't get the beforeClose event

ex. I am click the mask background, then into w-drawer's beforeClose event, then do something, return true or false 

if true close the drawer
if false keep the drawer
