### ISSUE TITLE
Material Icon doesn't work on production 

### ISSUE THREAD

**Issue by Qwanjai** [antoniandre/wave-ui#72]
When i used w-icon with material icon ligatures it's worked fine on localhost but when i deployed project on production , those icon didn't show or display

**Comment by antoniandre** [comment]
You may have a problem in the way you use material icons, since the Wave UI documentation itself is using the material icons with the ligatures on the w-icon page.

I recommend to open the example in Codepen and reproduce.
Hope it helps. :)
