### ISSUE TITLE
SCSS customizations seem to cause `Undefined mixin` errors

### ISSUE THREAD

**Issue by GuDzpoz** [antoniandre/wave-ui#75]
I set up months ago following the [`#Customization Via SCSS (optional)`](https://antoniandre.github.io/wave-ui/customization`) guide and it worked fine by then. But it seems some SCSS styling has been moved to `_mixins.scss` and it is causing my build to fail:
```
Syntax Error: SassError: Undefined mixin.
   ╷
59 │     @include default-transition;
   │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
```
I fixed this by manually adding `@import 'wave-ui/src/wave-ui/scss/_mixins';` in my customized `_variables.scss` and reproduced it with a new repository created with `vue create` (with plugins of version `4.5.15`) after repeating steps in [Getting Started](https://antoniandre.github.io/wave-ui/getting-started) and [Customization](https://antoniandre.github.io/wave-ui/customization). Have I done something wrong or does the guide need some update? Thank you!

**Comment by antoniandre** [comment]
Hi @GuDzpoz 

Thanks for reporting and for the details.
This should now be fixed in version 1.45.2

Please reopen if not solved! :)
