### ISSUE TITLE
Floating label doesn't float when value is 0

### ISSUE THREAD

**Issue by turbobuilt** [antoniandre/wave-ui#77]
Hi @antoniandre sorry for another bug.  But this one is a lot easier to fix!  I have an input with value 0, and the labels don't float.  Should be a pretty simple fix.  Here's a codepen:

https://codepen.io/dbobby/pen/ExwwJaJ?editors=1000

**Comment by antoniandre** [comment]
Hi @turbobuilt, 
Thanks for reporting and for the Codepen, very useful. 👍 
This is now fixed in version 1.45.5, much simpler bug indeed!

(Make sure you target the latest version in your Codepen when you refresh)
hope it helps, please reopen if not solved :)

**Comment by turbobuilt** [comment]
Hi @antoniandre  I can't test it out because I'm on v2x, and because the project I'm on is not in a state to be deployed right now.  Thanks for fixing the bug.  It was so clever to figure out that it happens only on https.  If I have a problem I will let you know.  Thanks so much for the hard work.
