### ISSUE TITLE
Incomplete 'Submission to Server' example

### ISSUE THREAD

**Issue by BrianBut** [antoniandre/wave-ui#8]
The documentation on form submission to server is incomplete. The sentence 'Then the form will be submitted in another tab to a fake test.php.' is quite mysterious. Hints on how this might be done would be very helpful.

Additionally the sentence 'The w-form prevents the form submission by default - for modern usage where an AJAX call is made on success (see the last example: Advanced validation).' is unhelpful as there is no Advanced validation example. I also need this.

**Comment by antoniandre** [comment]
Hi @BrianBut, thanks for reporting.
I have updated the documentation about the w-form direct submission and fixed the link to the last example of the page.
Hope it helps.
