### ISSUE TITLE
w-select prematurely disappears when closing a dialog

### ISSUE THREAD

**Issue by macjuul** [antoniandre/wave-ui#82]
Hey!

When placing a w-select inside a dialog and closing the dialog with a transition, you can see the input field vanish before the dialog has closed, creating a jump in the height of the card.

![msedge_nkjVsPEDZM](https://user-images.githubusercontent.com/7606171/156877285-8d535d36-3026-44f8-8f08-5692dc4c1eb3.gif)

I'm using wave-ui version 1.49.2 on Vue 2. I tried looking at the source code however couldn't find a reason as to why it happens 🤷

**Comment by macjuul** [comment]
The code is actually open source 🙂

https://github.com/StarlaneStudios/vindigo/blob/906def2a29d26afc0f0e5f11eda30dccc8fc69ca/packages/vindigo-client/components/project/CreationDialogs.vue#L147

I can confirm it's not the `v-if="isEditingNewLabel"` condition on the parent div as the label isn't affected. From what can see in devtools it looks like the actual `w-select__selection-wrap` element disappears the moment the transition starts while the `w-select` stays behind. I'm also seeing the same behavior for all w-selects inside w-dialogs.

**Comment by antoniandre** [comment]
Hi @macjuul,
Thanks for the repro. 
Just an update that I am working on that - it's a lot more complex than I initially thought.

**Comment by antoniandre** [comment]
Hi @macjuul, this is now fixed in version 1.51.0.
Hope it helps, please reopen if not solved. :)
