### ISSUE TITLE
w-dialog not closing sometimes and gets stuck in open mode

### ISSUE THREAD

**Issue by welpie21** [antoniandre/wave-ui#86]
I'm kinda in a weird situation currently. The w-dialog does not close sometimes. If you click a certain amount or click at a certain speed it won't emit a close event.

I'm not sure if this is in vue 2. but it's definitely in vue 3. i've also noticed the issue on the documentation page. especially the first 'open dialog' button.

https://antoniandre.github.io/wave-ui/w-dialog

The gif i've attached, I spammed actually outside when it got stuck and it didn't emit any close event.

![msedge_duSvsxLMaI](https://user-images.githubusercontent.com/14811347/160609816-b8d76a5d-a80f-44cb-99d5-4814cc7be4fa.gif)

**Comment by luc122c** [comment]
I've had the same issue when rapidly opening and closing a dialog programmatically. It seems to get confused and be half open, half closed.

**Comment by antoniandre** [comment]
Hi @welpie21, @luc122c,
Thanks for reporting. This is now fixed in version 2.36.0 and 1.53.0 (legacy).
Please reopen if not solved :)
