### ISSUE TITLE
Problem export on vite

### ISSUE THREAD

**Issue by Qwanjai** [antoniandre/wave-ui#87]
I have installed wave-ui and tailwind over vite and then tryna do some customization to disable wave-ui layout. I have tried on this guide 
https://antoniandre.github.io/wave-ui/customization  but got error with "Missing "./src/wave-ui" export in "wave-ui" package"
![image](https://user-images.githubusercontent.com/52848386/162934079-b7c1c66c-a25a-4780-8d3e-371438545d72.png)
Is there any solutions to fix this ?

**Comment by antoniandre** [comment]
Hi @Qwanjai, would you be able to share a reproduction link?
You can use StackBlitz to quickly spin up a Vite + Vue 3 project: https://stackblitz.com/edit/vite

**Comment by Qwanjai** [comment]
@antoniandre   this is my demo project on StackBlitz :  [https://stackblitz.com/edit/vitejs-vite-vyaset?file=vite.config.js](https://stackblitz.com/edit/vitejs-vite-vyaset?file=vite.config.js)  
hope it doesn't bother you too much.

**Comment by antoniandre** [comment]
Thanks for the repro @Qwanjai, it helped.
The customization through the Wave UI `src/` is now possible on Vite since version 2.36.2.
Here is a working demo: https://stackblitz.com/edit/vitejs-vite-wvuhlv?file=package.json

Hope it helps. Please reopen if not solved :)
