### ISSUE TITLE
w-textarea does not autogrow (or shrink) when v-model is updated

### ISSUE THREAD

**Issue by obliojoe** [antoniandre/wave-ui#88]
I have a `w-textarea` using `v-model` binding. If I update the model with a long blob of text, the textarea does not autogrow as expected (alternatively, it does not shrink to shorter text content). 

After the content is updated, if I focus the textarea and type any character, it will immediately grow or shrink to the correct size. 

I also noticed that each time I update the model, it autogrows to the size of the **previous** content. In the example below you can see this by clicking the button multiple times.

Here is an example of what I am running into (hope IU set this up correctly):
https://stackblitz.com/edit/vue-pb2h8t?file=src/App.vue

Thanks!

**Comment by antoniandre** [comment]
Hi @obliojoe,
This is now fixed in version 1.53.2.
Please reopen if not solved :)

**Comment by obliojoe** [comment]
> Hi @obliojoe, This is now fixed in version 1.53.2. Please reopen if not solved :)

Thank you so much! But, please pardon my ignorance. I'm running version 2.36.2. Are there 2 different versions?

**Comment by obliojoe** [comment]
> Hi @obliojoe, This is now fixed in version 1.53.2. Please reopen if not solved :)

Hi @antoniandre ... will this be fixed in v3 as well? I'm running 2.36.2 (vue 3) but it looks like this fix was in the legacy version. Thank you!

**Comment by antoniandre** [comment]
Of course, released in version 2.36.3. :)

**Comment by obliojoe** [comment]
> Of course, released in version 2.36.3. :) Your stackblitz works now.

It's a thing of beauty. Thanks again.
