### ISSUE TITLE
Couldn't import variables.scss during customization

### ISSUE THREAD

**Issue by chandutalkin** [antoniandre/wave-ui#90]
Hi,
I followed [Customiazion in Wave UI](https://antoniandre.github.io/wave-ui/customization) but after adding 
"@import 'wave-ui/src/wave-ui/scss/_variables';" statement to scss/_variables.scss 
I am getting below error. 

Error: Missing "./src/wave-ui/scss/_variables" export in "wave-ui" package

Can you please help me with this. I referred previous issues but couldn't solve it.
Thanks.

**Comment by antoniandre** [comment]
Hi @chandutalkin,
sorry for the delay. Thanks for reporting, this is now fixed in version 2.40.1.
Hope it helps, please reopen if not solved. :)
