### ISSUE TITLE
Unable to set wave ui option 

### ISSUE THREAD

**Issue by Qwanjai** [antoniandre/wave-ui#91]
As i mentioned in the last issue https://github.com/antoniandre/wave-ui/issues/87  the layout conflict was solved (thanks  a lot ) but i got a new issue , i want to set my own colors option  like this in my main.js  
` new WaveUI({
  colors: {
    primary: '#9ac332',
    secondary: '#5d9a26'
  }
})` 
 but it still use the default colors not the colors that i set , i use the same config as this demo u gave  me : https://stackblitz.com/edit/vitejs-vite-cur2qm?file=src%2FApp.vue,src%2Fmain.js

**Comment by antoniandre** [comment]
Hi @Qwanjai,
Thanks for reporting, this is now fixed in version 2.40.0.
Update the package.json of your stackblitz and reload :)
Please reopen if not solved
