### ISSUE TITLE
No documentation for templates

### ISSUE THREAD

**Issue by llamicron** [antoniandre/wave-ui#92]
I'm new to this framework so forgive me if I'm just missing something. In the [code for a dialog](https://antoniandre.github.io/wave-ui/w-dialog), templates are used like this:
```html
<template #title>
    <!-- more content here -->
</template>
```

I can't seem to find any documentation about this template or what templates are available. Are the docs for this just not written yet, or am I missing something? Thanks for any help you can provide.

**Comment by antoniandre** [comment]
Hi @llamicron,
The documentation is complete. To use a w-dialog you just need the `<w-dialog>` tag with inside it (before the closing tag), whatever free content you want, and with html if you want. That will be the content of the dialog.
If you want a title to this dialog, you can use the prestyled `#title` slot, that’s what <template #title>´ is for but not mandatory.

in the documentation, the examples are presented first and bellow you can find the potential slots available if there are for this component. If you are not familiar with slots, you should read about it in the vue documentation to understand more the concept. 
Hope it helps :)

**Comment by antoniandre** [comment]
Closed due to inactivity. please reopen if not solved.

**Comment by llamicron** [comment]
Ah, I see. I didn't know those were called slots, I think I've been using those in a different way. Thanks!
