### ISSUE TITLE
Is there a component for multi-level tree panel ?

### ISSUE THREAD

**Issue by kuchaguangjie** [antoniandre/wave-ui#94]
e.g the tree panel at left,

**Comment by antoniandre** [comment]
Hi @kuchaguangjie, thanks for the suggestion. I'll add it to my to do :)

**Comment by antoniandre** [comment]
Hi @kuchaguangjie, there is now a new tree component: https://antoniandre.github.io/wave-ui/w-tree
Let me know if you're missing a feature in there.

**Comment by guxin0123** [comment]
![1684208357200](https://github.com/antoniandre/wave-ui/assets/1772307/70075c66-8981-4705-b5d1-20f94d38e0a4)

@antoniandre   Can you add a select style and a hover style?

**Comment by antoniandre** [comment]
hi @guxin0123, for the CSS style please follow the thread in #108.
