### ISSUE TITLE
Feature request for table component

### ISSUE THREAD

**Issue by KleinSamuel** [antoniandre/wave-ui#96]
Hey, first of all great library I really enjoy working with it! Super clean and many great features.

I am primarily building sites that display data so the Table component is of great use for me.

The pagination component would be really great (its already in development I  think) so I am looking forward to it.

Filtering and sorting my data is usually perfomed in the backend and not the frontend (way more horsepower there and also the database technology can be used to efficiently sort and filter). 
So I would like to disable the sorting feature of the table in two ways:
1. Disable the sorting completely (no arrows for indication in the header row)
2. Keep the indication and events but disable the sorting functionality because if want to mutate the content myself.

Thanks and keep up the good work! :)

**Comment by antoniandre** [comment]
Hi @KleinSamuel,
Thanks for your feedback and support, I appreciate it.
I'll keep you posted when I have a new release for you, I'll work on it soon :)

**Comment by antoniandre** [comment]
Hi @KleinSamuel, from version 2.46.0 & 1.60.0, you can now perform a server side sorting on a table and still benefit from the Wave UI sorting UI.

The pagination will come later.

**Comment by iamgabrielsoft** [comment]
Can I work on the pagination?

**Comment by antoniandre** [comment]
Hi @KleinSamuel,
I'm sorry it took so long but here it is, the pagination is now part of the w-table component:
https://antoniandre.github.io/wave-ui/w-table#pagination

If you use it, you can give me feedback if you need extra functionality, and if it makes sense that it is in the Wave UI codebase I will add it. :)

Let me know if you have any questions.

**Comment by antoniandre** [comment]
This issue seems to be resolved by now. Feel free to reopen if anything looks wrong :)
